### ISSUE TITLE
Cannot insert pages with section titles starting with $

### ISSUE THREAD

**Issue by jrnold** [spencermountain/dumpster-dive#15]
When importing into mongodb `helper.js` chokes if there are keys beginning with a dollar sign. This
seems to happen with section titles. From a quick search I think the error message occurs from [this section](https://en.wikipedia.org/wiki/Subway_(restaurant)#.245_footlongs) in the Subway page.

```
Error: key $5 footlongs must not start with '$'
    at serializeInto (/home/ubuntu/wikipedia-to-mongodb/node_modules/bson/lib/bson/parser/serializer.js:751:19)
    at serializeObject (/home/ubuntu/wikipedia-to-mongodb/node_modules/bson/lib/bson/parser/serializer.js:308:18)
    at serializeInto (/home/ubuntu/wikipedia-to-mongodb/node_modules/bson/lib/bson/parser/serializer.js:776:17)
    at serializeObject (/home/ubuntu/wikipedia-to-mongodb/node_modules/bson/lib/bson/parser/serializer.js:308:18)
    at serializeInto (/home/ubuntu/wikipedia-to-mongodb/node_modules/bson/lib/bson/parser/serializer.js:618:17)
    at serializeObject (/home/ubuntu/wikipedia-to-mongodb/node_modules/bson/lib/bson/parser/serializer.js:308:18)
    at serializeInto (/home/ubuntu/wikipedia-to-mongodb/node_modules/bson/lib/bson/parser/serializer.js:776:17)
    at BSON.serialize (/home/ubuntu/wikipedia-to-mongodb/node_modules/bson/lib/bson/bson.js:58:27)
    at Query.toBin (/home/ubuntu/wikipedia-to-mongodb/node_modules/mongodb-core/lib/connection/commands.js:140:25)
    at Pool.write (/home/ubuntu/wikipedia-to-mongodb/node_modules/mongodb-core/lib/connection/pool.js:984:23)
events.js:182
      throw er; // Unhandled 'error' event
      ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Job.update (/home/ubuntu/wikipedia-to-mongodb/node_modules/kue/lib/queue/job.js:832:17)
    at Job.reattempt (/home/ubuntu/wikipedia-to-mongodb/node_modules/kue/lib/queue/job.js:585:23)
    at Job.<anonymous> (/home/ubuntu/wikipedia-to-mongodb/node_modules/kue/lib/queue/job.js:616:14)
    at Job.<anonymous> (/home/ubuntu/wikipedia-to-mongodb/node_modules/kue/lib/queue/job.js:555:7)
    at normal_reply (/home/ubuntu/wikipedia-to-mongodb/node_modules/redis/index.js:721:21)
    at RedisClient.return_reply (/home/ubuntu/wikipedia-to-mongodb/node_modules/redis/index.js:819:9)
    at JavascriptRedisParser.returnReply (/home/ubuntu/wikipedia-to-mongodb/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/home/ubuntu/wikipedia-to-mongodb/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/home/ubuntu/wikipedia-to-mongodb/node_modules/redis/index.js:274:27)
```

What's the best way to escape those keys?

**Comment by spencermountain** [comment]
ah!
yeah nice find. we should definitely address this.

hey,  in the newest version of [wtf_wikipedia](https://github.com/spencermountain/wtf_wikipedia), we're not storing it as an object anymore, so maybe that is smarter, and I should update this library too.
it's a [pretty big change](https://github.com/spencermountain/wtf_wikipedia/blob/master/changelog.md#200) to the response format, so will be a major update

**Comment by spencermountain** [comment]
yeah, can't start with a $ or contain a '.'

i think that's it. will have to do some kinda escaping.
will look into it this week.

**Comment by jrnold** [comment]
No problem - messy data is gonna do its thing. Thanks for this project, it's great! I've was looking around at the landscape of wikipedia-to-plaintext projects (though mostly python ones) to put together a corpus for NLP stuff.  I really like the approach, and that it is based on the official parser.
 
Once I finally realized realized what was going on (I don't do much - if anything in javascript) it wasn't bad.I have a fix in the fork linked earlier in this thread. But it looks like the update to wtf_wikipedia addresses it in a much better ways anyway.

**Comment by spencermountain** [comment]
hey, think i got this, wanna try it in v2?

just note that [other stuff](https://github.com/spencermountain/wikipedia-to-mongodb/blob/master/changelog.md) has changed a fair amount too.
cheers

**Comment by jrnold** [comment]
Looks awesome. Thanks! I'll try it out as soon as the English wikipedia dump downloads

**Comment by jrnold** [comment]
Seems like there's still some issues when there are no headings? 

```
ubuntu@ip-172-31-40-20:~/wikipedia-to-mongodb$ node src/worker.js
/home/ubuntu/wikipedia-to-mongodb/node_modules/wtf_wikipedia/src/parse/section/table.js:8
  if (str.match(/\|/)) {
         ^
TypeError: Cannot read property 'match' of null
    at parseHeading (/home/ubuntu/wikipedia-to-mongodb/node_modules/wtf_wikipedia/src/parse/section/table.js:8:10)
    at parse_table (/home/ubuntu/wikipedia-to-mongodb/node_modules/wtf_wikipedia/src/parse/section/table.js:32:15)
    at /home/ubuntu/wikipedia-to-mongodb/node_modules/wtf_wikipedia/src/parse/section/table.js:99:12
    at Array.map (<anonymous>)
    at Object.findTables [as table] (/home/ubuntu/wikipedia-to-mongodb/node_modules/wtf_wikipedia/src/parse/section/table.js:98:19)
    at parseSection (/home/ubuntu/wikipedia-to-mongodb/node_modules/wtf_wikipedia/src/parse/section/index.js:14:16)
    at Object.makeSections [as section] (/home/ubuntu/wikipedia-to-mongodb/node_modules/wtf_wikipedia/src/parse/section/index.js:38:15)
    at Object.main [as parse] (/home/ubuntu/wikipedia-to-mongodb/node_modules/wtf_wikipedia/src/parse/index.js:38:22)
    at Object.parse (/home/ubuntu/wikipedia-to-mongodb/src/doPage.js:50:18)
    at /home/ubuntu/wikipedia-to-mongodb/src/worker.js:25:14
```

**Comment by spencermountain** [comment]
hey thanks, looks like an issue in the wtf_wikipedia parser, are you able to find the article that triggers this?
happy to fix it today

**Comment by spencermountain** [comment]
lemme know if you are still seeing this, think we got it fixed.
