### ISSUE TITLE
Type error while loading data into mongo using dumpster

### ISSUE THREAD

**Issue by mrashwin15** [spencermountain/dumpster-dive#44]
Followed the steps to download english wiki dump, completed up to extract process but while adding data into mongo it is showing this error:-

TypeError: data[k].text is not a function
    at Object.keys.forEach (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/templates/misc.js:126:25)
    at Array.forEach (<anonymous>)
    at Object.subject bar (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/templates/misc.js:125:23)
    at doTemplate (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/templates/index.js:35:31)
    at templates.top.forEach (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/templates/index.js:69:12)
    at Array.forEach (<anonymous>)
    at Object.allTemplates [as templates] (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/templates/index.js:68:17)
    at doSection (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/section/index.js:21:16)
    at Object.splitSections [as section] (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/section/index.js:52:15)
    at main (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/document/index.js:47:22)

I also tried dumpster ./my/wikipedia-dump.xml --images false after doing this it will give error
 
TypeError: data[k].text is not a function
    at Object.keys.forEach (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/templates/misc.js:126:25)
    at Array.forEach (<anonymous>)
    at Object.subject bar (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/templates/misc.js:125:23)
    at doTemplate (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/templates/index.js:35:31)
    at templates.top.forEach (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/templates/index.js:69:12)
    at Array.forEach (<anonymous>)
    at Object.allTemplates [as templates] (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/templates/index.js:68:17)
    at doSection (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/section/index.js:21:16)
    at Object.splitSections [as section] (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/section/index.js:52:15)
    at main (/usr/local/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/document/index.js:47:22)

**Comment by mrashwin15** [comment]
![screenshot from 2018-06-09 10-39-29](https://user-images.githubusercontent.com/20479707/41187886-6b8cbcec-6bd1-11e8-9368-e2ab4615b8eb.png)

**Comment by spencermountain** [comment]
hey @mrashwin15 , thanks for the detailed bug report. I'll look at getting this fixed laster this week.
just looks like a bug.
cheers

**Comment by spencermountain** [comment]
oh hey, it looks like @dmh43 fixed this in this [pr](https://github.com/spencermountain/wtf_wikipedia/pull/117).

should be fixed in v3.3.0.
Lemme know how it goes.
