### ISSUE TITLE
Encoding of table keys

### ISSUE THREAD

**Issue by j-rausch** [spencermountain/dumpster-dive#60]
Hi, thanks so much for all the recent updates to the parser and dumpster-dive!
I just ran into following errors on version `3.6.0`:

```
...
   #0  - Art
   #0  - Agnostida
   #0  - Abortion
   #0  - Abstract (law)
   #0  - American Revolutionary War
   #0  - Ampere
   #0  - Algorithm
   #0  - Annual plant
====error!===
Error: key Dante]] ''L'Inferno'', Canto IV. 131–135 must not contain '.'
    at serializeInto (/lfs/raiders10/hdd/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:914:19)
    at serializeObject (/lfs/raiders10/hdd/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/lfs/raiders10/hdd/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:728:17)
    at serializeObject (/lfs/raiders10/hdd/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/lfs/raiders10/hdd/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:728:17)
    at serializeObject (/lfs/raiders10/hdd/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/lfs/raiders10/hdd/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at serializeObject (/lfs/raiders10/hdd/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/lfs/raiders10/hdd/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:728:17)
    at serializeObject (/lfs/raiders10/hdd/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
   #0  - Anthophyta
   #0  - Atlas (disambiguation)
   #0  - Mouthwash
   #0  - Alexander the Great
...
```

**Comment by toxuin** [comment]
Seeing the same thing on latest 3.6.0 en wiki.

**Comment by j-rausch** [comment]
Did a bit more digging. This specific error stems from a `wikitable` on https://en.wikipedia.org/wiki/Aristotle.

**Comment by spencermountain** [comment]
yeah, sorry bout this. will take a look

**Comment by spencermountain** [comment]
got this fixed in 3.6.1, lemme know if you see something else
cheers

**Comment by j-rausch** [comment]
Hey @spencermountain, this error seems to come up in `4.0.0` again:
Here's the logging output for one worker with batch_size=1:
```
...
   #0  - British Indian Ocean Territory/Communications
   #0  - British Indian Ocean Territory/Transportation
   #0  - British Indian Ocean Territory/Military
   #0  - British Indian Ocean Territory/Transnational issues
   #0  - Geography of the British Virgin Islands
 #0  +1 pages  -  3ms - "Geography of the British Virgin Islands"
   #0  - Demographics of the British Virgin Islands
 #0  +1 pages  -  9ms - "Demographics of the British Virgin Islands"
   #0  - Economy of the British Virgin Islands
   ====DB write error (worker 0)===
Error: key additional information not from cia world factbook taken from [http://www.bvi.org.uk/news_item.asp?news_id must not contain '.'
    at serializeInto (/home/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:914:19)
    at serializeObject (/home/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/home/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:728:17)
    at serializeObject (/home/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/home/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at serializeObject (/home/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/home/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:728:17)
    at serializeObject (/home/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/home/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at BSON.serialize (/home/jrausch/git/dumpster-dive/node_modules/bson/lib/bson/bson.js:63:28)
   #0  - Telecommunications in the British Virgin Islands
 #0  +1 pages  -  6ms - "Telecommunications in the British Virgin Islands"
   #0  - Transport in the British Virgin Islands
 #0  +1 pages  -  58ms - "Transport in the British Virgin Islands"
...
```

**Comment by aymansalama** [comment]
Hey @spencermountain thank you man for the hard work. I really appreciate it and value it. @j-rausch I actually face the same error
I have counted 657 errors 
```
sudo grep '====DB write error' nohup.out | wc -l 
657
```
sample of the error
```
====DB write error (worker 6)===
Error: key int. darts league must not contain '.'
    at serializeInto (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:914:19)
    at serializeObject (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:728:17)
    at serializeObject (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at serializeObject (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:728:17)
    at serializeObject (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at BSON.serialize (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/bson.js:63:28)
```

**Comment by spencermountain** [comment]
hey, thanks. Sounds reasonable. I'll check it out today.

**Comment by aymansalama** [comment]
@spencermountain I am not using custom output. i run dumpster command with standard parameter from linux command line without any modification.

**Comment by spencermountain** [comment]
hey, i've moved this into wtf_wikipedia, so it is cleaner to maintain now, and can be used in `custom` functions, too.
Lemme know if anybody sees any period-in-keys encoding errors `4.0.2` onwards
thanks
