### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by SeansRightHere** [spencermountain/dumpster-dive#62]
Does it modify the existing file, or output to a different file?

**Comment by aymansalama** [comment]
Super cool project. thank you so much. I was working on similar project for couple of months. By the way, I am offering my help if you need a dirty hand. i have some experience. let me know if you need to know more about me. 

I got dumpster-dive and it seems to be working on Google Cloud GCP. forgive my naive questions below:
1. Even dumpster recognise that I have 24 Core on GCP, still it run on 6 cores only. 
2. Time estimate doesn't work well. the predicted time is too small compared to reality 
3. I was working on enwiki, part 1 which is 30K++ pages, it only uploaded 600++ pages. I am not sure if there multi pages per page. I am still investigating. Possibly there are many duplicates
4. for the whole enwiki, i got tens of errors like:


====error!===
{ MongoError: BSONObj size: 16927305 (0x1024A49) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"
    at /usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  ok: 0,
  errmsg:
   'BSONObj size: 16927305 (0x1024A49) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"',
  code: 10334,
  codeName: 'BSONObjectTooLarge',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }




====error!===
{ MongoError: BSONObj size: 16891063 (0x101BCB7) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"
    at /usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  ok: 0,
  errmsg:
   'BSONObj size: 16891063 (0x101BCB7) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"',
  code: 10334,
  codeName: 'BSONObjectTooLarge',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }


====error!===
{ MongoError: BSONObj size: 16954395 (0x102B41B) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"
    at /usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  ok: 0,
  errmsg:
   'BSONObj size: 16954395 (0x102B41B) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"',
  code: 10334,
  codeName: 'BSONObjectTooLarge',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }



====error!===
{ MongoError: BSONObj size: 16912181 (0x1020F35) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"
    at /usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  ok: 0,
  errmsg:
   'BSONObj size: 16912181 (0x1020F35) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"',
  code: 10334,
  codeName: 'BSONObjectTooLarge',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
====error!===
{ MongoError: BSONObj size: 16912181 (0x1020F35) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"
    at /usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  ok: 0,
  errmsg:
   'BSONObj size: 16912181 (0x1020F35) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"',
  code: 10334,
  codeName: 'BSONObjectTooLarge',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
====error!===
{ MongoError: BSONObj size: 16912181 (0x1020F35) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"
    at /usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  ok: 0,
  errmsg:
   'BSONObj size: 16912181 (0x1020F35) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"',
  code: 10334,
  codeName: 'BSONObjectTooLarge',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
====error!===
{ MongoError: BSONObj size: 16912181 (0x1020F35) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"
    at /usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/usr/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  ok: 0,
  errmsg:
   'BSONObj size: 16912181 (0x1020F35) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"',
  code: 10334,
  codeName: 'BSONObjectTooLarge',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
 
attached the current working logs

[dumpster-log-pat1.txt](https://github.com/spencermountain/dumpster-dive/files/2387845/dumpster-log-pat1.txt)

**Comment by SeansRightHere** [comment]
I’m not really a coder, sorry. If put directly to DB, is there a way I can
specify output file?

**Comment by spencermountain** [comment]
@SeansRightHere yeah, you can look around them mongo documentation for that. When you start mongo, you can specify where it saves your database.
`mongod --dbpath=/whatever/data/path`

**Comment by aymansalama** [comment]
@spencermountain excellent work. Thank you for your reply. the  scripts are still running and cpus are still hot. I am running everything on GCP. I will let you know if i get more errors. I have another notice, but not sure yet if it is a valid remark. I tried to run two dumpster command for two different dataset, and i think when one is running, the other goes silent and never progress. 
When i try to load this file of wikidatawiki, it takes too long and then the loaded data in mongo has a lot special characters and unicodes. sampel file name wikidatawiki-20180901-pages-articles.xml.bz2 47.1 GB
whoever it works well on enwiki-latest-pages-articles.xml and the data is loaded properly. 

Let me know how i can help. i have good experience in web development. you can email me with the details on ay.salama@gmail.com

**Comment by spencermountain** [comment]
whoa, wikidata has an xml dump? is it in the same format?
I doubt this library would work on a wikidata export, but it would probably see the xml and try to do stuff.
what does the wikidata xml look like? can you do a `head` command on it?

**Comment by SeansRightHere** [comment]
It had20-30 errors on mine but 6 hours later, said it complied the 147Gb of
Wiki xml

**Comment by aymansalama** [comment]
@spencermountain wikidata avail its dump in three format JSON, RDF, XML. Ref: https://www.wikidata.org/wiki/Wikidata:Database_download 
Actually dumpster is working on it very hard. it processes it and upload some data. Visually you can see encoding issues in the uploaded data. Actually as far as i understand, it doesn't make sense to use dumpster to load wikidata in xml format. Since wikidata already availed its data in JSON which you can upload directly to mongo. am I correct ?  

i was uploading the files of wikidata for experimental purposes. 

Here is the head -150 of the xml of wikidata. i have attached the file. Of course you can download the whole files from the link above. 


[head-150-wikidatawiki-20180901-pages-articles1.xml-p1p235321.txt](https://github.com/spencermountain/dumpster-dive/files/2391128/head-150-wikidatawiki-20180901-pages-articles1.xml-p1p235321.txt)






<mediawiki xmlns="http://www.mediawiki.org/xml/export-0.10/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mediawiki.org/xml/export-0.10/ http://www.mediawiki.org/xml/export-0.10.xsd" version="0.10" xml:lang="en">
  <siteinfo>
    <sitename>Wikidata</sitename>
    <dbname>wikidatawiki</dbname>
    <base>https://www.wikidata.org/wiki/Wikidata:Main_Page</base>
    <generator>MediaWiki 1.32.0-wmf.19</generator>
    <case>first-letter</case>
    <namespaces>
      <namespace key="-2" case="first-letter">Media</namespace>
      <namespace key="-1" case="first-letter">Special</namespace>
      <namespace key="0" case="first-letter" />
      <namespace key="1" case="first-letter">Talk</namespace>
      <namespace key="2" case="first-letter">User</namespace>
      <namespace key="3" case="first-letter">User talk</namespace>
      <namespace key="4" case="first-letter">Wikidata</namespace>
      <namespace key="5" case="first-letter">Wikidata talk</namespace>
      <namespace key="6" case="first-letter">File</namespace>
      <namespace key="7" case="first-letter">File talk</namespace>
      <namespace key="8" case="first-letter">MediaWiki</namespace>
      <namespace key="9" case="first-letter">MediaWiki talk</namespace>
      <namespace key="10" case="first-letter">Template</namespace>
      <namespace key="11" case="first-letter">Template talk</namespace>
      <namespace key="12" case="first-letter">Help</namespace>
      <namespace key="13" case="first-letter">Help talk</namespace>
      <namespace key="14" case="first-letter">Category</namespace>
      <namespace key="15" case="first-letter">Category talk</namespace>
      <namespace key="120" case="first-letter">Property</namespace>
      <namespace key="121" case="first-letter">Property talk</namespace>
      <namespace key="122" case="first-letter">Query</namespace>
      <namespace key="123" case="first-letter">Query talk</namespace>
      <namespace key="146" case="first-letter">Lexeme</namespace>
      <namespace key="147" case="first-letter">Lexeme talk</namespace>
      <namespace key="828" case="first-letter">Module</namespace>
      <namespace key="829" case="first-letter">Module talk</namespace>
      <namespace key="1198" case="first-letter">Translations</namespace>
      <namespace key="1199" case="first-letter">Translations talk</namespace>
      <namespace key="2300" case="first-letter">Gadget</namespace>
      <namespace key="2301" case="first-letter">Gadget talk</namespace>
      <namespace key="2302" case="case-sensitive">Gadget definition</namespace>
      <namespace key="2303" case="case-sensitive">Gadget definition talk</namespace>
      <namespace key="2600" case="first-letter">Topic</namespace>
    </namespaces>
  </siteinfo>
  <page>
    <title>Wikidata:Main Page/Content</title>
    <ns>4</ns>
    <id>1</id>
    <revision>
      <id>665868355</id>
      <parentid>624548684</parentid>
      <timestamp>2018-04-15T22:38:57Z</timestamp>
      <contributor>
        <username>Dataeast0000001</username>
        <id>2952466</id>
      </contributor>
      <comment>removing unwanted space</comment>
      <model>wikitext</model>
      <format>text/x-wiki</format>
      <text xml:space="preserve">&lt;div lang=&quot;{{{lang|{{int:lang}}}}}&quot; class=&quot;mw-content-{{dir|{{{lang|{{int:lang}}}}}}}&quot;&gt;
&lt;noinclude&gt;&lt;languages /&gt;&lt;/noinclude&gt;
&lt;!--------------------------------------------
                 HEADER
---------------------------------------------&gt;
{{Main Page/Header new
 | welcome = &lt;translate&gt;&lt;!--T:1--&gt;

**Comment by spencermountain** [comment]
yes, that's correct.
thanks, wikidata is so weird!

**Comment by spencermountain** [comment]
gonna close this, think problems are covered elsewhere
