### ISSUE TITLE
Error on keys with periods

### ISSUE THREAD

**Issue by noodlez04** [spencermountain/dumpster-dive#69]
Hi,
Since I've been using the new version (4.0.1), I've been experiencing errors when keys (titles, I guess? unique Id?) contain periods, for example:
```
Error: key entertainment ed. must not contain '.'
    at serializeInto (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:914:19)
    at serializeObject (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:728:17)
    at serializeObject (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at serializeObject (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:728:17)
    at serializeObject (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at BSON.serialize (/usr/lib/node_modules/dumpster-dive/node_modules/bson/lib/bson/bson.js:63:28)
```

This happens both with a custom function and by simply running `dumpster`

**Comment by spencermountain** [comment]
hey, thanks @noodlez04 gonna merge this with #60 
should have a fix this week.
