### ISSUE TITLE
MongoError: BSONObj Size

### ISSUE THREAD

**Issue by sackio** [spencermountain/dumpster-dive#78]
**Node v11.14.0
NPM v6.9.0
Mongod v3.4.20
Ubuntu Linux 16.04
dumpster-dive v5.1.2**

I'm getting the following error repeatedly:

```
   ====DB write error (worker 0)===
{ MongoError: BSONObj size: 16857622 (0x1013A16) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"
    at /home/ben/.nvm/versions/node/v11.14.0/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/home/ben/.nvm/versions/node/v11.14.0/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/home/ben/.nvm/versions/node/v11.14.0/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/home/ben/.nvm/versions/node/v11.14.0/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/home/ben/.nvm/versions/node/v11.14.0/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:150:17)
  ok: 0,
  errmsg:
   'BSONObj size: 16857622 (0x1013A16) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"',
  code: 10334,
  codeName: 'Location10334',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
```
The process runs but only saves a single page in Mongo throughout -- which it seems to write at the very beginning of the process.

Seeing a lot of messages like:

```
     current: 1 pages - "true"     

-- 500  duplicate pages --
 #5  +0 pages  -  1s - "true"
-- 500  duplicate pages --
 #2  +0 pages  -  900ms - "true"
-- 500  duplicate pages --
 #1  +0 pages  -  1s - "true"
-- 500  duplicate pages --
 #4  +0 pages  -  944ms - "true"
-- 500  duplicate pages --
 #2  +0 pages  -  1s - "true"

     current: 1 pages - "true"     

      ─── worker #0 ───: 
         +4,500 pages
         -7,350 redirects
         -206 disambig
         0 ns
      ─── worker #2 ───: 
         +9,500 pages
         -21,113 redirects
         -521 disambig
         0 ns
      ─── worker #3 ───: 
         +4,500 pages
         -7,353 redirects
         -206 disambig
         0 ns
```

**Comment by sackio** [comment]
Original issue was with the English Wikipedia version. Have since tried with the Afrikaans version and seeing the same issue -- one article gets inserted into Mongo, and insertion size limit issues after that. I also cloned the latest version of the project, but I'm seeing the same issues.

**Comment by spencermountain** [comment]
hey Ben, sometimes if the batch_size is too high, it will be > 16mb.
you could try this:
```
let options = {
  file: path,
  db: dbName,
  verbose: true,
  batch_size:10
}
dumpster(options)
```

but if it's happening consistently, best to add a `console.log` to the records, to see what it's trying to write. it's possible the page xml being parsed properly, for some reason
a log [anywhere in here](https://github.com/spencermountain/dumpster-dive/blob/master/src/worker/03-write-db.js#L19) should do it.
lemme know
cheers

**Comment by sackio** [comment]
Thanks -- I tried playing with the batch size and seemed to be getting same issue -- so XML parsing issues make sense -- might be trying to dump the entire file or something after parsing fails. I'll see what I can log. Thanks for your help -- and this amazing project.

**Comment by spencermountain** [comment]
any luck?
