### ISSUE TITLE
The process does not end on Windows

### ISSUE THREAD

**Issue by vyank** [spencermountain/dumpster-dive#81]
Ran the process with file and db on windows. The process does not end, it hangs after showing 'worker 6 has finished' 

There are messaging appearing: current: 107,920 pages - "undefined"

When I try to end the process, below exception occurs.

one sec, cleaning-up the workers...
--uncaught top-process error--
ProcessTerminatedError: cancel after 0 retries!
    at ...\pool.js:111:39
    at Array.forEach (<anonymous>)
    at WorkerNodes.handleWorkerExit (...\pool.js:110:14)
    at Worker.<anonymous> (...\pool.js:160:44)
    at Worker.emit (events.js:203:13)
    at WorkerProcess.<anonymous> (...\worker.js:39:18)
    at Object.onceWrapper (events.js:291:20)
    at WorkerProcess.emit (events.js:203:13)
    at ChildProcess.<anonymous> (...\worker\process.js:42:41)
    at Object.onceWrapper (events.js:291:20) {
  name: 'ProcessTerminatedError',
  message: 'cancel after 0 retries!'

**Comment by spencermountain** [comment]
thanks @vyank. I don't have a windows computer to test on, but my understanding is that others have gotten this to work.
Fwiw, it sounds like a [worker-nodes](https://github.com/allegro/node-worker-nodes) error - is there anyway you can make sure some worker-nodes examples work on your machine?

is 107k pages the expected end?
thanks

**Comment by vyank** [comment]
Thanks a lot for your reply. Sorry for my delayed reply. Expected pages looks good. But the process does not end. Let me check with worker-node and see if that works fine.
