### ISSUE TITLE
Process stopped dumping after a while

### ISSUE THREAD

**Issue by khan990** [spencermountain/dumpster-dive#85]
I am trying to dump english wiki into mongodb.

After about 5 hours, I see that the process stops dumping new pages.

![image](https://user-images.githubusercontent.com/2551269/84116877-ef68db00-aa30-11ea-8b2c-51b4f6b18a60.png)

![image](https://user-images.githubusercontent.com/2551269/84117020-2dfe9580-aa31-11ea-9602-3d4c70bf498a.png)

![image](https://user-images.githubusercontent.com/2551269/84117546-f93f0e00-aa31-11ea-8b1c-6503646875aa.png)

If I am not wrong, I should be expecting 6 million plus pages.

> P.S. Its an ubuntu 18.04 machine with nodejs 12.18.0

**Comment by spencermountain** [comment]
hi Jasim, yeah that's funny, it looks like all workers stopped writing at the same time.
Yes, I'd expect it to run further, and then provide a nice finish message.

That made me think it's a mongo connection pool issue. But also, if I'm correct, using 35mb of memory means that it's not actually parsing files any more.

I'm stumped by this one, but happy to help. May be helpful to throw in some console.logs to see what that end-state is actually doing. I've never seen this sort of issue before.
cheers

**Comment by khan990** [comment]
This time I ran the dump without `pm2`. Still the same. It took a long checking duplicates in the db from the last process. Then added some new pages, and then stopped again.

```
root@rnd:~# tail -n 100 /mnt/HC_Volume_5753563/wikipedia/dumpster-dive/output.log


     current: 3,071,107 pages - "British Army incremental infantry companies"


     current: 3,071,107 pages - "British Army incremental infantry companies"


     current: 3,071,107 pages - "British Army incremental infantry companies"


     current: 3,071,107 pages - "British Army incremental infantry companies"


     current: 3,071,107 pages - "British Army incremental infantry companies"


     current: 3,071,107 pages - "British Army incremental infantry companies"


     current: 3,071,107 pages - "British Army incremental infantry companies"


     current: 3,071,107 pages - "British Army incremental infantry companies"


     current: 3,071,107 pages - "British Army incremental infantry companies"
```


```
root@rnd:/mnt/HC_Volume_5753563/wikipedia/dumpster-dive# node ./bin/report.js enwiki
(node:21327) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead


   ----------- 3,071,107 pages total -----------

AggregationCursor {
  _readableState: ReadableState {
    objectMode: true,
    highWaterMark: 16,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: null,
    pipesCount: 0,
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    emitClose: true,
    autoDestroy: false,
    destroyed: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: null
  },
  readable: true,
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  operation: AggregateOperation {
    options: { readPreference: [ReadPreference] },
    ns: MongoDBNamespace { db: 'enwiki', collection: '$cmd' },
    readPreference: ReadPreference { mode: 'primary', tags: undefined },
    readConcern: undefined,
    writeConcern: undefined,
    explain: false,
    fullResponse: true,
    target: 'pages',
    pipeline: [],
    hasWriteStage: false,
    cursorState: {
      cursorId: null,
      cmd: {},
      documents: [],
      cursorIndex: 0,
      dead: false,
      killed: false,
      init: false,
      notified: false,
      limit: 0,
      skip: 0,
      batchSize: 1000,
      currentLimit: 0,
      transforms: undefined,
      raw: undefined
    }
  },
  pool: null,
  server: null,
  disconnectHandler: undefined,
  bson: BSON {},
  ns: 'enwiki.$cmd',
  namespace: MongoDBNamespace { db: 'enwiki', collection: '$cmd' },
  cmd: {},
  options: {
    readPreference: ReadPreference { mode: 'primary', tags: undefined }
  },
  topology: NativeTopology {
    _events: [Object: null prototype] {
      authenticated: [Function],
      error: [Array],
      timeout: [Array],
      close: [Array],
      parseError: [Array],
      fullsetup: [Array],
      all: [Array],
      reconnect: [Array],
      commandStarted: [Function],
      commandSucceeded: [Function],
      commandFailed: [Function],
      serverOpening: [Function],
      serverClosed: [Function],
      serverDescriptionChanged: [Function],
      serverHeartbeatStarted: [Function],
      serverHeartbeatSucceeded: [Function],
      serverHeartbeatFailed: [Function],
      topologyOpening: [Function],
      topologyClosed: [Function],
      topologyDescriptionChanged: [Function],
      joined: [Function],
      left: [Function],
      ping: [Function],
      ha: [Function],
      connectionPoolCreated: [Function],
      connectionPoolClosed: [Function],
      connectionCreated: [Function],
      connectionReady: [Function],
      connectionClosed: [Function],
      connectionCheckOutStarted: [Function],
      connectionCheckOutFailed: [Function],
      connectionCheckedOut: [Function],
      connectionCheckedIn: [Function],
      connectionPoolCleared: [Function],
      open: [Function]
    },
    _eventsCount: 35,
    _maxListeners: Infinity,
    s: {
      id: 0,
      options: [Object],
      seedlist: [Array],
      state: 'connected',
      description: [TopologyDescription],
      serverSelectionTimeoutMS: 30000,
      heartbeatFrequencyMS: 10000,
      minHeartbeatFrequencyMS: 500,
      Cursor: [Function: Cursor],
      bson: BSON {},
      servers: [Map],
      sessionPool: [ServerSessionPool],
      sessions: Set {},
      promiseLibrary: [Function: Promise],
      credentials: undefined,
      clusterTime: null,
      connectionTimers: Set {}
    },
    [Symbol(kCapture)]: false,
    [Symbol(waitQueue)]: Denque { _head: 3, _tail: 3, _capacityMask: 3, _list: [Array] }
  },
  cursorState: {
    cursorId: null,
    cmd: {},
    documents: [],
    cursorIndex: 0,
    dead: false,
    killed: false,
    init: false,
    notified: false,
    limit: 0,
    skip: 0,
    batchSize: 1000,
    currentLimit: 0,
    transforms: undefined,
    raw: undefined
  },
  logger: Logger { className: 'Cursor' },
  s: {
    numberOfRetries: 5,
    tailableRetryInterval: 500,
    currentNumberOfRetries: 5,
    state: 0,
    promiseLibrary: [Function: Promise],
    explicitlyIgnoreSession: false
  },
  [Symbol(kCapture)]: false
}

```

I will try to run it in `verbose` mode, if there is any. Lets see what we get...

**Comment by khan990** [comment]
Well this time it worked using `pm2`. I will share the parameters that I used this time. It finished the job with 5,059,476  pages in total.
Following is end log:
```
root@rnd:~# pm2 logs 0
[TAILING] Tailing last 15 lines for [0] process (change the value with --lines option)
/root/.pm2/logs/wiki-dump-error.log last 15 lines:
0|wiki-dum | MongoNetworkError: connection 2 to 127.0.0.1:27017 timed out
0|wiki-dum |     at /mnt/HC_Volume_5753563/wikipedia/dumpster-dive/node_modules/mongodb/lib/cmap/connection.js:78:15
0|wiki-dum |     at Map.forEach (<anonymous>)
0|wiki-dum |     at Socket.<anonymous> (/mnt/HC_Volume_5753563/wikipedia/dumpster-dive/node_modules/mongodb/lib/cmap/connection.js:77:20)
0|wiki-dum |     at Socket.emit (events.js:315:20)
0|wiki-dum |     at Socket._onTimeout (net.js:481:8)
0|wiki-dum |     at listOnTimeout (internal/timers.js:549:17)
0|wiki-dum |     at processTimers (internal/timers.js:492:7) {
0|wiki-dum |   [Symbol(mongoErrorContextSymbol)]: {}
0|wiki-dum | }

/root/.pm2/logs/wiki-dump-out.log last 15 lines:
0|wiki-dum |    #0  - Highway 49 (Georgia)
0|wiki-dum |    #0  - Georgia 49
0|wiki-dum |    #0  - S Chandrashekhar
0|wiki-dum |    #0  - Robert B. (Racehorse) Smith
0|wiki-dum |    #0  - Pullman doctrine
0|wiki-dum |    #0  - Georgia Route 49
0|wiki-dum |    #0  - Stadia (unit of length)
0|wiki-dum |    #0  - Georgia State Highway 49
0|wiki-dum |    #0  - The Secret World of Santa Claus
0|wiki-dum |  #0  +6 pages  -  18ms - "Passerelle (Luxembourg)"
0|wiki-dum |
0|wiki-dum |
0|wiki-dum |     💪  worker #0 has finished 💪
0|wiki-dum |       - 1 workers still running -
0|wiki-dum |
```

I used the following params:
```
pm2 start ./bin/dumpster.js --  ../enwiki-20200520-pages-articles.xml --verbose=true --plaintext=true --batch_size=100
```
