### ISSUE TITLE
MongoServerSelectionError: connection <monitor> to 127.0.0.1:27017 timed out

### ISSUE THREAD

**Issue by shreyasminocha** [spencermountain/dumpster-dive#87]
I was parsing an enwiki dump, but exactly 1,206,500 pages in, I ran into an error:

```
MongoServerSelectionError: connection <monitor> to 127.0.0.1:27017 timed out
    at Timeout._onTimeout (/usr/local/lib/node_modules/dumpster-dive/node_modules/mongodb/lib/core/sdam/topology.js:430:30)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { 'localhost:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  },
  [Symbol(mongoErrorContextSymbol)]: {}

     current: 1,206,500 pages - "London Bombs"


     current: 1,206,500 pages - "London Bombs"


     current: 1,206,500 pages - "London Bombs"

     […]
}
```

I <kbd>^C</kbd>'ed it and restarted, but soon enough (101,500 pages in) it halts with the same error and the same current page: "London Bombs".

<kbd>^C</kbd>'ing, outputs this:

```
^CError: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:835:20)
    at ChildProcess.target.send (internal/child_process.js:706:19)
    at WorkerProcess.exit (/usr/local/lib/node_modules/dumpster-dive/node_modules/worker-nodes/lib/worker/process.js:63:20)
    at Worker.stop (/usr/local/lib/node_modules/dumpster-dive/node_modules/worker-nodes/lib/worker.js:125:22)
    at /usr/local/lib/node_modules/dumpster-dive/node_modules/worker-nodes/lib/pool.js:337:24
    at Array.forEach (<anonymous>)
    at Queue.forEach (/usr/local/lib/node_modules/dumpster-dive/node_modules/worker-nodes/lib/util/queue.js:38:29)
    at WorkerNodes.checkShutdown (/usr/local/lib/node_modules/dumpster-dive/node_modules/worker-nodes/lib/pool.js:333:27)
    at WorkerNodes.terminate (/usr/local/lib/node_modules/dumpster-dive/node_modules/worker-nodes/lib/pool.js:316:14)
    at WorkerPool.cleanup (/usr/local/lib/node_modules/dumpster-dive/src/02-Worker-pool.js:88:22) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

<details>
<summary><code>mongod</code> output</summary>
<pre>
[…]
2020-08-05T02:27:54.331+0530 I  NETWORK  [conn6260] received client metadata from 127.0.0.1:57766 conn6260: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }
2020-08-05T02:27:54.331+0530 I  NETWORK  [conn6258] end connection 127.0.0.1:57764 (5 connections now open)
2020-08-05T02:27:54.336+0530 I  NETWORK  [conn6260] end connection 127.0.0.1:57766 (4 connections now open)
2020-08-05T02:27:54.336+0530 I  NETWORK  [listener] connection accepted from 127.0.0.1:57768 #6262 (5 connections now open)
2020-08-05T02:27:54.340+0530 I  NETWORK  [conn6261] received client metadata from 127.0.0.1:57767 conn6261: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }
2020-08-05T02:27:54.342+0530 I  NETWORK  [listener] connection accepted from 127.0.0.1:57769 #6263 (6 connections now open)
2020-08-05T02:27:54.342+0530 I  NETWORK  [conn6262] received client metadata from 127.0.0.1:57768 conn6262: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }
2020-08-05T02:27:54.342+0530 I  NETWORK  [conn6263] received client metadata from 127.0.0.1:57769 conn6263: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }
2020-08-05T02:27:54.343+0530 I  NETWORK  [listener] connection accepted from 127.0.0.1:57770 #6264 (7 connections now open)
2020-08-05T02:27:54.343+0530 I  NETWORK  [conn6259] end connection 127.0.0.1:57765 (6 connections now open)
2020-08-05T02:27:54.360+0530 I  NETWORK  [conn6202] end connection 127.0.0.1:57651 (5 connections now open)
2020-08-05T02:27:54.364+0530 I  NETWORK  [conn6203] end connection 127.0.0.1:57652 (4 connections now open)
2020-08-05T02:27:54.451+0530 I  NETWORK  [conn6261] end connection 127.0.0.1:57767 (3 connections now open)
2020-08-05T02:27:54.897+0530 I  COMMAND  [conn6262] command admin.$cmd command: isMaster { ismaster: true, client: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }, compression: [], $db: "admin" } numYields:0 reslen:257 locks:{} protocol:op_query 554ms
2020-08-05T02:27:54.897+0530 I  COMMAND  [conn6263] command admin.$cmd command: isMaster { ismaster: true, client: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }, compression: [], $db: "admin" } numYields:0 reslen:257 locks:{} protocol:op_query 554ms
2020-08-05T02:27:54.897+0530 I  NETWORK  [conn6264] received client metadata from 127.0.0.1:57770 conn6264: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }
2020-08-05T02:27:55.032+0530 I  COMMAND  [conn6264] command admin.$cmd command: isMaster { ismaster: true, client: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }, compression: [], $db: "admin" } numYields:0 reslen:257 locks:{} protocol:op_query 135ms
2020-08-05T02:27:55.032+0530 I  NETWORK  [conn6263] end connection 127.0.0.1:57769 (2 connections now open)
2020-08-05T02:27:55.032+0530 I  NETWORK  [conn6262] end connection 127.0.0.1:57768 (1 connection now open)
2020-08-05T02:27:55.034+0530 I  NETWORK  [conn6264] end connection 127.0.0.1:57770 (0 connections now open)
2020-08-05T02:28:04.397+0530 I  NETWORK  [listener] connection accepted from 127.0.0.1:57773 #6265 (1 connection now open)
2020-08-05T02:28:04.401+0530 I  NETWORK  [conn6265] received client metadata from 127.0.0.1:57773 conn6265: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }
2020-08-05T02:28:04.407+0530 I  NETWORK  [listener] connection accepted from 127.0.0.1:57774 #6266 (2 connections now open)
2020-08-05T02:28:04.408+0530 I  NETWORK  [conn6266] received client metadata from 127.0.0.1:57774 conn6266: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }
2020-08-05T02:30:54.937+0530 I  COMMAND  [conn6266] command enwiki.pages command: aggregate { aggregate: "pages", pipeline: [ { $match: {} }, { $group: { _id: 1, n: { $sum: 1 } } } ], cursor: {}, lsid: { id: UUID("3074bafd-4089-4812-8edc-e828a2c7f96e") }, $db: "enwiki" } planSummary: COLLSCAN keysExamined:0 docsExamined:1206500 cursorExhausted:1 numYields:11609 nreturned:1 reslen:125 locks:{ ReplicationStateTransition: { acquireCount: { w: 11611 } }, Global: { acquireCount: { r: 11611 } }, Database: { acquireCount: { r: 11611 } }, Collection: { acquireCount: { r: 11611 } }, Mutex: { acquireCount: { r: 2 } } } storage:{ data: { bytesRead: 8146762687, timeReadingMicros: 163100870 } } protocol:op_msg 170271ms
2020-08-05T02:30:54.972+0530 I  NETWORK  [conn6265] end connection 127.0.0.1:57773 (1 connection now open)
2020-08-05T02:30:54.972+0530 I  NETWORK  [conn6266] end connection 127.0.0.1:57774 (0 connections now open)
2020-08-05T02:31:05.014+0530 I  NETWORK  [listener] connection accepted from 127.0.0.1:57797 #6267 (1 connection now open)
2020-08-05T02:31:05.015+0530 I  NETWORK  [conn6267] received client metadata from 127.0.0.1:57797 conn6267: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }
2020-08-05T02:31:05.024+0530 I  NETWORK  [listener] connection accepted from 127.0.0.1:57798 #6268 (2 connections now open)
2020-08-05T02:31:05.025+0530 I  NETWORK  [conn6268] received client metadata from 127.0.0.1:57798 conn6268: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }
2020-08-05T02:34:11.822+0530 I  COMMAND  [conn6268] command enwiki.pages command: aggregate { aggregate: "pages", pipeline: [ { $match: {} }, { $group: { _id: 1, n: { $sum: 1 } } } ], cursor: {}, lsid: { id: UUID("629f3133-a365-48d7-a3e1-fc86424203a8") }, $db: "enwiki" } planSummary: COLLSCAN keysExamined:0 docsExamined:1206500 cursorExhausted:1 numYields:11761 nreturned:1 reslen:125 locks:{ ReplicationStateTransition: { acquireCount: { w: 11763 } }, Global: { acquireCount: { r: 11763 } }, Database: { acquireCount: { r: 11763 } }, Collection: { acquireCount: { r: 11763 } }, Mutex: { acquireCount: { r: 2 } } } storage:{ data: { bytesRead: 8146762691, timeReadingMicros: 176435204 } } protocol:op_msg 186793ms
2020-08-05T02:34:11.852+0530 I  NETWORK  [conn6267] end connection 127.0.0.1:57797 (1 connection now open)
2020-08-05T02:34:11.854+0530 I  NETWORK  [conn6268] end connection 127.0.0.1:57798 (0 connections now open)
2020-08-05T02:34:21.867+0530 I  NETWORK  [listener] connection accepted from 127.0.0.1:57848 #6269 (1 connection now open)
2020-08-05T02:34:21.868+0530 I  NETWORK  [conn6269] received client metadata from 127.0.0.1:57848 conn6269: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }
2020-08-05T02:34:21.875+0530 I  NETWORK  [listener] connection accepted from 127.0.0.1:57849 #6270 (2 connections now open)
2020-08-05T02:34:21.876+0530 I  NETWORK  [conn6270] received client metadata from 127.0.0.1:57849 conn6270: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }
2020-08-05T02:36:32.628+0530 I  COMMAND  [conn6270] command enwiki.pages command: aggregate { aggregate: "pages", pipeline: [ { $match: {} }, { $group: { _id: 1, n: { $sum: 1 } } } ], cursor: {}, lsid: { id: UUID("d9354c0f-9233-4b1c-be3c-a1acb087232b") }, $db: "enwiki" } planSummary: COLLSCAN keysExamined:0 docsExamined:1206500 cursorExhausted:1 numYields:11052 nreturned:1 reslen:125 locks:{ ReplicationStateTransition: { acquireCount: { w: 11054 } }, Global: { acquireCount: { r: 11054 } }, Database: { acquireCount: { r: 11054 } }, Collection: { acquireCount: { r: 11054 } }, Mutex: { acquireCount: { r: 2 } } } storage:{ data: { bytesRead: 8146757481, timeReadingMicros: 126277255 } } protocol:op_msg 130750ms
2020-08-05T02:36:32.667+0530 I  NETWORK  [conn6269] end connection 127.0.0.1:57848 (1 connection now open)
2020-08-05T02:36:32.678+0530 I  NETWORK  [conn6270] end connection 127.0.0.1:57849 (0 connections now open)
2020-08-05T02:36:42.686+0530 I  NETWORK  [listener] connection accepted from 127.0.0.1:57863 #6271 (1 connection now open)
2020-08-05T02:36:42.688+0530 I  NETWORK  [conn6271] received client metadata from 127.0.0.1:57863 conn6271: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }
2020-08-05T02:36:42.697+0530 I  NETWORK  [listener] connection accepted from 127.0.0.1:57864 #6272 (2 connections now open)
2020-08-05T02:36:42.698+0530 I  NETWORK  [conn6272] received client metadata from 127.0.0.1:57864 conn6272: { driver: { name: "nodejs", version: "3.5.6" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "19.5.0" }, platform: "'Node.js v14.4.0, LE (unified)" }
[…]
</pre>
</details>

**Comment by spencermountain** [comment]
hey Shreyas, that sounds like a tough one. Not sure why the server times out at these locations. Nothing wrong with that london bombs page in the parser.
My intuition is the mongo server is crashing for some system reason, and not the script.
You may want to use the `skip` param to continue where you left off.
I'm not sure what else - mongo sure does seem to be a handful
Let me know how that goes.
cheers

**Comment by shreyasminocha** [comment]
> My intuition is the mongo server is crashing for some system reason, and not the script.

Yeah, you may be right actually.

> You may want to use the `skip` param to continue where you left off.

Cool, I'll try that.

I'll close this on the assumption that it was a mongo issue and I'll reopen if I find something that suggests otherwise.

**Comment by shreyasminocha** [comment]
Yep, you were right about this. Thanks!
